---
- name: 下载mysql repos
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: 安装mysql
  yum: name=mysql-server state=latest

- name: 复制my.cnf
  copy: src=my.cnf dest=/etc/ 

- name: 创建mysql目录
  file: path=/data/mysql state=directory owner=mysql recurse=yes
  notify: restart mysql

- name: 启动数据库
  service: name=mysqld state=started
